weatherreport:
  config:
    fetchWeatherInfoByCityNameURL: "http://api.openweathermap.org/data/2.5/weather?q={city}&appId="
    fetchWeatherInfoByLatLonURL: "http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appId="
    appId: ""
